L-W-payments/asaas-payment

- docker-compose.yml
- grails-app/conf/application.yml
Através desse pr, o docker é adicionado ao projeto com o intuito de facilitar a criação, configuração e utilização de banco de dados da aplicação.
Formas de uso:
`docker compose up -d` - Na raiz do projeto para iniciar o banco de dados.
`docker compose stop` - Na raiz do projeto para parar o banco de dados.
> Adicionando docker

- src/main/groovy/com/miniasaaslw/utils/StateUtils.groovy
Com esse PR é adicionado a implementação do StateUtils para validar um estado seguindo a regra:
O estado precisa possuir duas letras alfabéticas, exemplo: PE, MG, SP.
> Validação de Estado

- grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy
Nesse PR é implementado uma série validações que foram criadas anteriormente para os atributos do domain Payer. Sendo eles:
Validação de nome;
Validação de número de celular;
Validação de estado;
Validação de cep;
Validação de CPF;
Validação de CNPJ
> Adicionando validações do Payer

- grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy
- src/main/groovy/com/miniasaaslw/repository/customer/CustomerRepository.groovy
Nesse PR é feito uma checagem no banco de dados na hora de criação de um customer para saber se já possui um email igual.
Além disso, foi feito uma pequena alteração na condicional de verificação do cpfCnpj para padronização sem afetar seu uso.
> Bloqueando criação de customers com emails duplicados

- grails-app/assets/javascripts/PayerListController.js
- grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
- grails-app/views/payer/list.gsp
- grails-app/views/payer/templates/_tableContent.gsp
Agora é possível visualizar pagadores que foram deletados, para futuramente ser possível restaurá-los
Foi adicionado um botão de "restaurar" que por enquanto ainda não é funcional, é só um indicativo de que aquele pagador em específico na listagem está deletado
[81](https://github.com/L-W-payments/asaas-payment/pull/81)
https://github.com/orgs/L-W-payments/projects/1?pane=issue&itemId=65886613
Tela com o filtro:
Quando é aplicado o filtro de exibir deletados:
> Adicionando filtro para exibir pagadores deletados

- grails-app/assets/javascripts/PaymentListController.js
- grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
- grails-app/views/payment/list.gsp
- grails-app/views/payment/templates/_tableContent.gsp
Agora é possível visualizar cobranças que foram deletadas, para futuramente ser possível restaurá-las
Foi adicionado um botão de "restaurar" que por enquanto ainda não é funcional, é só um indicativo de que aquela cobrança em específico na listagem está deletada
[90](https://github.com/L-W-payments/asaas-payment/pull/90)
[124](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65886600)
Filtro desativado:
Filtro ativado:
> Adicionando filtro para exibir cobranças deletadas

- grails-app/views/payment/checkout.gsp
Antes o botão de pagar não estava funcionando, agora é possível pagar uma cobrança.
[Tarefa 150](https://github.com/L-W-payments/asaas-payment/issues/150)
> Corrigindo tela de pagamento

- grails-app/taglib/com/miniasaaslw/DateTimeTagLib.groovy
- grails-app/views/payer/templates/_tableContent.gsp
- grails-app/views/payment/checkout.gsp
- grails-app/views/payment/show.gsp
- grails-app/views/payment/templates/_tableContent.gsp
Agora está sendo usado a taglib de formatação de datas nos gsps
[108](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65037209)
> Usando a taglib de formatação de datas nos gsps

- README.md
- grails-app/assets/javascripts/PayerListController.js
- grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
- grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy
- grails-app/views/payer/templates/_tableContent.gsp
Agora o botão de restaurar um pagador na listagem está funcionando, permitindo que pagadores deletados previamente possam ser restaurados.
Também foi alterado o uso do service, sendo obrigatório ser passado o cliente do pagador, para evitar restaurar pagadores de outros clientes.
[Tarefa 159](https://github.com/L-W-payments/asaas-payment/issues/159)
> Implementando restauração do pagador

- README.md
- grails-app/assets/javascripts/PaymentListController.js
- grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
- grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
- grails-app/views/payment/list.gsp
- grails-app/views/payment/templates/_tableContent.gsp
Agora o botão de restaurar um pagador na listagem está funcionando, permitindo que pagadores deletados previamente possam ser restaurados.
Também foi alterado o uso do service, sendo obrigatório ser passado o cliente da cobrança, para evitar restaurar cobranças de outros clientes.
[Tarefa 160](https://github.com/L-W-payments/asaas-payment/issues/160)
> Implementando restauração da cobrança

- grails-app/views/payer/show.gsp
Agora o título da página aparece corretamente como **Visualizar pagador**,  sendo chamado antes de **Cadastro de pagador**
[Tarefa 176](https://github.com/L-W-payments/asaas-payment/issues/176)
> Alterando nome da pagina de visualização de pagador

- grails-app/assets/javascripts/PayerController.js
- grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
- grails-app/views/payer/show.gsp
- grails-app/views/payer/templates/_tableContent.gsp
Agora não temos dois métodos para apagar um payer, e foi implementado o modal no show quando é apertado no botão de deletar
[183](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66584021)
Modal no show do payer:
> [Payer] - Refactor - Refatorando "fetchDelete" para "delete"

- grails-app/taglib/com/miniasaaslw/FormatterTagLib.groovy
- grails-app/views/payer/templates/_tableContent.gsp
- grails-app/views/payment/checkout.gsp
- grails-app/views/payment/show.gsp
- grails-app/views/payment/templates/_tableContent.gsp
- grails-app/views/paymentReceipt/templates/_receipt.gsp
- src/main/groovy/com/miniasaaslw/entity/enums/PersonType.groovy
- src/main/groovy/com/miniasaaslw/utils/DateUtils.groovy
A DateTimeTagLib é refatorada para FormatterTagLib e é adicionado os métodos para formatar CPF, Cnpj e telefone.
Também foi adicionado um atributo a mais do formatter da data, para formatar para a data longa. 
[198](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66618148)
> [Taglib de formatação] - Adiciona formaters para CPF, CNPJ, Telefone e Data longa

- grails-app/conf/application.groovy
- grails-app/domain/com/miniasaaslw/domain/security/User.groovy
- grails-app/init/com/miniasaaslw/BootStrap.groovy
- grails-app/views/login/auth.gsp
Com esse PR é adicionado o relacionamento entre o Customer e User, onde um usuário possui um cliente. O cliente não possui uma lista de usuários para evitar carregamento de todos os usuários quando um Customer é chamado.
Também foi alterado o uso de nome para e-mail na autenticação.
[PR 200](https://github.com/L-W-payments/asaas-payment/pull/200)
[Tarefa 204](https://github.com/L-W-payments/asaas-payment/issues/204)
> [Spring security 3] Criando relacionamento entre User e Customer

- grails-app/i18n/messages_pt_BR.properties
- grails-app/services/com/miniasaaslw/service/user/UserService.groovy
- src/main/groovy/com/miniasaaslw/repository/user/UserRepository.groovy
O erro ao tentar cadastrar um usuário com um email que já existe, agora é tratado
Antes estava a mensagem padrão do spring, agora é usado nossa mensagem personalizada
[220](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67034516
)
> [User] Trata erro de tentar cadastrar um usuário com um email já existente

- grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy
- src/main/groovy/com/miniasaaslw/repository/customer/CustomerRepository.groovy
Agora é utilizado o `CustomerRepository.query([search]).exists()` para consultar na base se algo já existe, removendo o método estático criado antes de ser implementado o repositório base do asaas
[237](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67199312)
> [Customer] Padronizar a checagem de existsBy email e CpfCnpj

- build.gradle
- grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
- src/main/groovy/com/miniasaaslw/utils/DateUtils.groovy
É corrigido o erro de validação da data de vencimento
- Não era possível criar uma cobrança que se vence no dia atual
- Acontecia porque a gente tava comparando com uma instância `new Date()`, que pega o dia atual, mas também a hora
- Então na hora de comparar utilizando o `before`, retornava false
- Foi criado um método no DateUtils que retorna a data atual as 00:00
[254](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67363975)
> [Bugfix] Refatoração da validação de data de vencimento da cobrança

- grails-app/assets/javascripts/LoginController.js
- grails-app/assets/stylesheets/login.scss
- grails-app/views/login/auth.gsp
Foi melhorada a responsividade da tela além de mostrar um feedback visual quando o usuário é redirecionado da tela de registro para tela de login após sua conta ter sido criada.
[PR 260](https://github.com/L-W-payments/asaas-payment/pull/260)
[Tarefa 263](https://github.com/L-W-payments/asaas-payment/issues/263)
Tela responsiva:
> Melhorando tela de login

- grails-app/services/com/miniasaaslw/service/user/UserService.groovy
Corrigindo Exception lançada errada, esse conflito ocorreu por causa da refatoração do nome `GenericException` para `BusinessException`
[274](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67499781)
> [Bugfix] Corrigindo exceção lançada errada

- grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy
Agora é redirecionado corretamente para a tela de login, com o params informando que o usuário acabou de ser criado
[278](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67507367)
> [Bugfix] Conserta redirect depois de cadastrar um novo customer

- grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
Agora na listagem de pagadores na hora de criar um payment, só aparece os payers daquele customer logado
Também redireciona para o show do payment depois da cobrança ser criada
[280](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67507600)
> [Bugfix] Conserta a listagem dos pagadores na hora de criar um payment, e redireciona pro show depois da criação
