L-W-payments/asaas-payment

build.gradle, grails-app/conf/application.yml
Esse PR contém as configurações de dependencia do driver do mysql, além do link direto com ele.
O username e password precisam ser alterados localmente de acordo com o usuário
Iremos criar o banco em um container docker depois para evitar esse problema.
=> Configurando database

src/main/groovy/com/miniasaaslw/utils/NameUtils.groovy
Com esse PR é adicionado a implementação do NameUtils para validar um nome de usuário seguindo a regra:
O nome precisa possuir ao menos 1 sobrenome;
O nome não pode conter espaço em branco no início ou no fim.
=> Validação de nome completo

grails-app/domain/com/miniasaaslw/domain/payment/Payment.groovy, src/main/groovy/com/miniasaaslw/entity/enums/payment/PaymentStatus.groovy, src/main/groovy/com/miniasaaslw/entity/enums/payment/PaymentType.groovy
Neste pr é adicionado o domínio de pagamento onde serão armazenado as informações de uma cobrança.
=> Criação do domínio de Pagamaneto

src/main/groovy/com/miniasaaslw/utils/CepUtils.groovy
Neste PR é criado o método de validação do CEP
=> Validação de CEP

README.md
Neste PR é adicionado um arquivo com regras de negócio, requisitos funcionais e requisitos não funcionais da aplicação.
=> Criação do README

grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy
Neste PR foram adicionadas as validações ao customer
=> Validando os atributos do Customer

grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy, src/main/groovy/com/miniasaaslw/repository/customer/CustomerRepository.groovy
Nesse PR é implementado uma validação no Customer para prevenir que pessoas se registrem com o mesmo CPF ou CNPJ.
=> Customer - Validar se o CPF ou CNPJ já está registrado

grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy, grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy, src/main/groovy/com/miniasaaslw/utils/CepUtils.groovy, src/main/groovy/com/miniasaaslw/utils/CpfCnpjUtils.groovy, src/main/groovy/com/miniasaaslw/utils/NameUtils.groovy, src/main/groovy/com/miniasaaslw/utils/PhoneUtils.groovy, src/main/groovy/com/miniasaaslw/utils/StateUtils.groovy
Neste PR é feito a refatoração de alguns métodos de validação, para deixar padronizado, seguindo o que foi proposto no livro de elite do asaas.
=> Padronizando nome dos métodos de validação

grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy, grails-app/views/payer/list.gsp
Nesse PR foi criado uma tela para listagem de pagadores junto com seu método list no PayerController.
Tela com pagadores:
Tela sem pagadores:
=> Criação da tela de listagem de pagadores

grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, src/main/groovy/com/miniasaaslw/adapters/payment/PaymentAdapter.groovy
Esse PR adiciona a base do Service para salvar um pagamento futuramente dentro da aplicação
=> Criando Service do Payment

src/main/groovy/com/miniasaaslw/repository/payer/PayerRepository.groovy
Nesse PR é adicionado uma query no PayerRepository para ser possível obter pagadores de um cliente.
=> Pegar pagadores de um cliente

src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy
Neste PR é criado o repositório do Payment para prosseguir com a criação do seu CRUD
=> Criando repositório do Payment

grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy, grails-app/domain/com/miniasaaslw/domain/customer/Customer.groovy, grails-app/domain/com/miniasaaslw/domain/payer/Payer.groovy, grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy, grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy, grails-app/views/payer/index.gsp, grails-app/views/payer/show.gsp, src/main/groovy/com/miniasaaslw/adapters/payer/PayerAdapter.groovy
Neste PR é adcionado o relacionamento entre os domains customer e payer.
Além de adcionar um select no front para selecionar qual customer está relacionado ao novo payer
=> Relacionamento entre Customer e Payer

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, src/main/groovy/com/miniasaaslw/utils/LoggedCustomer.groovy
Nesse PR é adicionado o endpoint de deletar cobrança junto com seu controller.
Também foi adicionada uma solução temporária que será utilizados em métodos da aplicação na qual precisa de um Customer (Cliente logado na aplicação)
=> Criando endpoint de deletar cobrança

grails-app/i18n/messages_pt_BR.properties, grails-app/views/payment/index.gsp, grails-app/views/payment/show.gsp
Nesse PR é adicionado o design da página de  pagamento
Resultado:
=> Criação da tela de pagamento

README.md, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, src/main/groovy/com/miniasaaslw/adapters/payment/PaymentAdapter.groovy
Neste PR foi adicionado os validadores para:
- Checkar se os campos são nulos
- Checkar se o customer e o payer relacionado a esse payment, existem
- Checkar se o valor é entre R$10 e R$10000
- Checkar se a data de vencimento é no futuro, e no máx 6 meses no futuro
- Checkar se a descrição tem no máximo 500 caracteres
=> Validando dados do payment

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, grails-app/views/payment/index.gsp, src/main/groovy/com/miniasaaslw/adapters/payment/PaymentAdapter.groovy, src/main/groovy/com/miniasaaslw/utils/DateUtils.groovy
Neste Pr é adcionando o endpoint chamando o save do Payment, juntamente com a sua view
Também foi adicionado um DateUtils, para ajudar a fazer o parse da Data.
Tela de cadastro de cobrança:
Depois da cobrança feita:
Lembrando, o alerta é temporário, enquanto a gente ainda não fez o list de cobranças, mas adicionei essa indicação visual para saber que deu tudo certo ao criar a cobrança
=> Tela de Cadastro de Cobrança 

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
Neste PR é adcionando uma '{' faltante que foi removida na hora da resolução de conflitos do merge anterior
=> Consertando Payment Controller

grails-app/views/layouts/main.gsp
Nesse PR é implementado o design do Navbar.
Primeiro resultado:
Menu do usuário:
Menu de notificações:
=> Adicionando perfil do usuário e notificações para o navbar

grails-app/domain/com/miniasaaslw/domain/notification/Notification.groovy, grails-app/domain/notification/Notification.groovy, src/main/groovy/com/miniasaaslw/entity/enums/NotificationPriority.groovy
Nesse PR é adicionado o domínio de notificações que será utilizado para armazenar notificações de clientes da aplicação.
=> Criando dominio de notificações

grails-app/domain/com/miniasaaslw/domain/payment/Payment.groovy, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
Neste PR é adicionado as constantes "MIN_VALUE" e "MAX_VALUE" para o domain de payment.
=> Adicionando constantes para o domain payment

.github/pull_request_template.md
Agore existe um template de pull request
https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65017992
=> Adicionando template de PR

grails-app/taglib/com/miniasaaslw/DateTimeTagLib.groovy, src/main/groovy/com/miniasaaslw/utils/DateUtils.groovy
Neste PR é adicionado uma taglib para auxiliar na formatação da data
=> Taglib de formatação de date

src/main/groovy/com/miniasaaslw/repository/Repository.groovy, src/main/groovy/com/miniasaaslw/utils/StringUtils.groovy
Neste PR é adicionando o repositório base, para depois implementar nos repositories dos domains
https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65222922
=> Adicionando Repositório Base

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/domain/com/miniasaaslw/domain/payment/Payment.groovy, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy
Neste PR é adicionado um id público (UUID) para que pessoas que não estejam logadas na aplicação possam acessar uma cobrança e pagar ela. Com isso evita pessoas maliciosas chutarem Ids incrementais como era anteriormente: 1, 2, 3...
Este PR depende do [PR 96](https://github.com/L-W-payments/asaas-payment/pull/96).
Resultado:
=> Adicionando id público para cobranças

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, grails-app/views/payment/checkout.gsp, grails-app/views/payment/show.gsp, src/main/groovy/com/miniasaaslw/entity/enums/payment/PaymentType.groovy
Neste PR é adicionado a visualização de uma cobrança
[Pr dependente](https://github.com/L-W-payments/asaas-payment/pull/96)
Tela de Visualização:
=> Visualização de Payment

grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy
Através desse PR será possível que a aplicação utilize desse endpoint para restaurar pagadores previamente deletados.
[Tarefa 134](https://github.com/L-W-payments/asaas-payment/issues/134)
=> Adicionando endpoint de restaurar um pagador deletado

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
Através desse PR será possível que a aplicação utilize desse endpoint para restaurar cobranças previamente deletadas.
[Tarefa 133](https://github.com/L-W-payments/asaas-payment/issues/133)
=> Adicionando endpoint de restaurar uma cobrança deletada

README.md, grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, grails-app/views/payment/show.gsp, src/main/groovy/com/miniasaaslw/entity/enums/payment/PaymentStatus.groovy, src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy
Agora é possível confirmar o recebimento em dinheiro
[100](https://github.com/L-W-payments/asaas-payment/pull/100)
https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=64795154
Tela quando o pagamento pode ser confirmado em dinheiro:
Tela quando o pagamento já foi confirmado:
=> Funcionalidade de confirmar recebimento em dinheiro

grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy, grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
Houve problema no merge do Payer Controller e do Customer Controller, este PR conserta
[142](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66257344)
=> Corrigindo erros do merge

grails-app/views/payment/show.gsp
Agora é possível acessar o pagador relacionado aquela cobrança na visualização dela
[138](https://github.com/orgs/L-W-payments/projects/1?pane=issue&itemId=66079500)
=> Linkando pagador na tela de cobrança

src/main/groovy/com/miniasaaslw/repository/customer/CustomerRepository.groovy, src/main/groovy/com/miniasaaslw/utils/LoggedCustomer.groovy
Foi implementado o novo repositório no CustomerRepository
[145](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66267303)
=> CustomerRepository - Implementando novo repositório

src/main/groovy/com/miniasaaslw/repository/notification/NotificationRepository.groovy
Com a implementação do novo repositório, estão sendo alterados os antigos repositórios.
[Tarefa 148](https://github.com/L-W-payments/asaas-payment/issues/148)
=> Adicionando novo repositório no NotificationRepository

grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy
Foi implementado o novo repositório no PaymentRepository
[147](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66267353)
=> PaymentRepository - Implementando novo repositório

grails-app/domain/com/miniasaaslw/domain/payment/Payment.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, grails-app/views/payment/checkout.gsp, grails-app/views/payment/index.gsp, grails-app/views/payment/show.gsp, grails-app/views/payment/templates/_table.gsp, grails-app/views/payment/templates/_tableContent.gsp, src/main/groovy/com/miniasaaslw/adapters/payment/PaymentAdapter.groovy, src/main/groovy/com/miniasaaslw/entity/enums/payment/BillingType.groovy
Foi renomeado "paymentType" para "billingType"
[117](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65571050)
=> Refatoração - Renomeando "paymentType" para "billingType"

grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, src/main/groovy/com/miniasaaslw/adapters/notification/NotificationAdapter.groovy
Agora é utilizado métodos estáticos para buildar o notificationAdapter, usando o mesmo padrão das notificações de Email
[188](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66614113)
=> [Notification] Refactor - Usando métodos estáticos para buildar o notificationAdapter

grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy, grails-app/views/payer/index.gsp, src/main/groovy/com/miniasaaslw/adapters/payer/PayerAdapter.groovy
Foi removido da tela de criação de payer o select de customer, agora está sendo utilizado o utils "LoggedCustomer"
[175](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66455418)
=> [Payer] Refactor - Removendo seleção de customer da tela de criação de payer

grails-app/views/payment/show.gsp, grails-app/views/payment/templates/_tableContent.gsp
Neste PR é adicionado o link da visualização do pagamento nas rows da listagem de cobranças, além da correção de um erro de import no show da cobrança
[190](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66614507)
=> [Payer] Adicionando link para a página de visualização de cobranças

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/views/payment/checkout.gsp
Alterando redirecionamento ao pagar uma cobrança ao invés de ser mandado para uma página que caso ele não seja o cliente, ele não tenha acesso.
[Tarefa 212](https://github.com/L-W-payments/asaas-payment/issues/212)
=> [Cobrança] Redirecionar de volta para mesma página ao pagar

grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
Agora o comprovante de pagamento é gerado automaticamente após um pagamento.
[PR 206](https://github.com/L-W-payments/asaas-payment/issues/206)
=> [Comprovante de pagamento] Gerando comprovante após pagar

grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/paymentreceipt/PaymentReceiptService.groovy
Corrigindo um problema onde o código das mensagens não estavam corretos.
[Tarefa 208](https://github.com/L-W-payments/asaas-payment/issues/208)
=> Resolvendo erro nas mensagens de erro do recibo

build.gradle, grails-app/conf/application.groovy, grails-app/conf/spring/resources.groovy, grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy, grails-app/controllers/com/miniasaaslw/controller/notification/NotificationController.groovy, grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy, grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/domain/com/miniasaaslw/domain/security/Role.groovy, grails-app/domain/com/miniasaaslw/domain/security/User.groovy, grails-app/domain/com/miniasaaslw/domain/security/UserRole.groovy, grails-app/init/com/miniasaaslw/BootStrap.groovy, src/main/groovy/com/miniasaaslw/security/UserPasswordEncoderListener.groovy
O spring boot foi adicionado ao projeto junto com a proteção de rotas.
[Tarefa 191](https://github.com/L-W-payments/asaas-payment/issues/191)
=> [Spring security] Adicionando a configuração inicial

grails-app/assets/stylesheets/login.scss, grails-app/views/login/auth.gsp, grails-app/views/templates/_lines.gsp
Com esse PR, será alterada a tela padrão de login do Spring Security.
[PR 193](https://github.com/L-W-payments/asaas-payment/pull/193)
[Tarefa 199](https://github.com/L-W-payments/asaas-payment/issues/199)
Tela com erro de login:
=> [Spring security 2] Adicionando tela de login

grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy, grails-app/services/com/miniasaaslw/service/user/UserService.groovy, src/main/groovy/com/miniasaaslw/repository/user/UserRepository.groovy
Neste PR foi criada a listagem de usuários para ser exibidas futuramente na página de usuários de um cliente.
[PR 214](https://github.com/L-W-payments/asaas-payment/pull/214)
[Tarefa 216](https://github.com/L-W-payments/asaas-payment/issues/216)
=> [Spring security 6] Criar endpoint de listagem de usuários

grails-app/controllers/com/miniasaaslw/controller/notification/NotificationController.groovy, grails-app/services/com/miniasaaslw/service/notification/NotificationService.groovy, grails-app/views/layouts/main.gsp, grails-app/views/templates/_navbar.gsp, grails-app/views/templates/_notifications.gsp, grails-app/views/templates/_sidebar.gsp
Com essa alteração foi as notificações do usuário não se expandir até o fim da tela como acontecia antigamente. Também foi adicionado links de redirecionamento da notificação.
[Tarefa 221](https://github.com/L-W-payments/asaas-payment/issues/221)
Antes da alteração:
Depois da alteração:
=> Refatorando notificações da aplicação e layout principal

grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy, grails-app/views/payer/index.gsp, grails-app/views/payer/list.gsp, grails-app/views/payer/show.gsp
A partir desse PR o sistema de pagador utiliza o usuário logado para criação, alteração e listagem.
[Tarefa 229](https://github.com/L-W-payments/asaas-payment/issues/229)
=> [Payer] Refatorar service e controller

grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/views/templates/_sidebar.gsp, grails-app/views/user/index.gsp, grails-app/views/user/templates/_userForm.gsp
É adicionada a tela de criação de usuário, acessível apenas para quem é Admin
Tabém é adicionado na sidebar o menu de usuários, também visível apenas para o Admin
[219](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67025310)
Tela de criação do usuário:
=> [User] Adicionando tela de criação de Usuário

grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/user/UserService.groovy, grails-app/views/user/show.gsp, grails-app/views/user/templates/_userForm.gsp
Agora é possível visualizar os dados de um usuário
- Um usuário admin, consegue ver as informações de outros, e de si mesmo
- Um usuário membro, consegue ver apenas as próprias informações
[224](https://github.com/L-W-payments/asaas-payment/pull/224)
[226](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67046114)
Tela de visualização:
=> [User 3] Tela de visualização do Usuário

grails-app/assets/javascripts/CustomerController.js, grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy, grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy, grails-app/views/customer/show.gsp, grails-app/views/layouts/main.gsp
A partir desse PR o Customer passou a utilizar o usuário logado do Spring Boot.
[Tarefa 227](https://github.com/L-W-payments/asaas-payment/issues/227)
=> [Customer] Refatorando service/controller

grails-app/assets/javascripts/UserListController.js, grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy, grails-app/views/templates/_sidebar.gsp, grails-app/views/user/list.gsp, grails-app/views/user/templates/_table.gsp, grails-app/views/user/templates/_tableContent.gsp, src/main/groovy/com/miniasaaslw/repository/user/UserRepository.groovy
[PR 224](https://github.com/L-W-payments/asaas-payment/pull/224)
[Tarefa 223](https://github.com/L-W-payments/asaas-payment/issues/223)
=> [User 2] Criando listagem de usuários

grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/user/UserService.groovy, grails-app/views/user/show.gsp, grails-app/views/user/templates/_userForm.gsp, src/main/groovy/com/miniasaaslw/adapters/user/UserAdapter.groovy
Agora é possível alterar a senha do usuário
- O admin consegue alterar tanto a dele, quanto a de outras usuários
- Também foi refatorado o "show" para exibir as mensagens de sucesso/erro quando o usuário for atualizado
[231](https://github.com/orgs/L-W-payments/projects/1?pane=issue&itemId=67050500)
=> [User] Update de senha do usuário

grails-app/controllers/com/miniasaaslw/controller/paymentreceipt/PaymentReceiptController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/paymentreceipt/PaymentReceiptService.groovy, grails-app/views/paymentReceipt/show.gsp
Agora, qualquer pessoa pode acessar o comprovante de pagamento
É adicionada a tratativa de erros do comprovante
Também é adicionado o a anotação `GrailsCompileStatic` no controller e no service do comprovante
Erro desconhecido:
Erro de não encontrado:
=> [PaymentReceipt] Refatoração do comprovante de pagamento

grails-app/controllers/com/miniasaaslw/UrlMappings.groovy, grails-app/controllers/com/miniasaaslw/controller/index/IndexController.groovy, grails-app/views/index.gsp, grails-app/views/index/index.gsp, grails-app/views/templates/_atlasCard.gsp, src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy, src/main/groovy/com/miniasaaslw/repository/paymentreceipt/PaymentReceiptRepository.groovy, src/main/groovy/com/miniasaaslw/utils/DateUtils.groovy
É adicionada a tela inicial do projeto
- Cards de visualização das cobranças do mês
- Cards de informações sobre a aplicação
[194](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66618018)
=> [Index] Adicionando index

grails-app/assets/javascripts/UserListController.js, grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/user/UserService.groovy, grails-app/views/user/list.gsp, grails-app/views/user/templates/_tableContent.gsp, src/main/groovy/com/miniasaaslw/repository/user/UserRepository.groovy
Com esse PR é possível deletar um usuário a partir do soft delete usando o próprio método do Spring Security. 
[Tarefa 243](https://github.com/L-W-payments/asaas-payment/issues/243)
=> [Spring security] Adicionando soft delete ao usuário

grails-app/assets/javascripts/UserListController.js, grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/user/UserService.groovy
Agora é possível que usuários previamente deletados pelos seus clientes possam ser restaurados.
[PR 245](https://github.com/L-W-payments/asaas-payment/pull/245)
[Tarefa 246](https://github.com/L-W-payments/asaas-payment/issues/246)
=> [Spring security 2] Adicionando restauração de usuário

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy, grails-app/views/payment/checkout.gsp, grails-app/views/payment/show.gsp, src/main/groovy/com/miniasaaslw/adapters/payment/PaymentAdapter.groovy
Com essa fatoração os endpoints de pagamento agora estão utilizando o usuário logado do Spring Security.
Foi ajustado a tela de visualização de uma cobrança.
**Também foram corrigidos alguns problemas:**
A descrição do pagamento não estava sendo salvada no banco de dados;
Caso o valor do pagamento fosse maior que 999 o tratamento no back-end dava erro;
O pagamento no front-end não podia ser pago caso estivesse expirado;
A validação de recebido não verifica se ele já havia sido pago em dinheiro; 
[Tarefa 234](https://github.com/L-W-payments/asaas-payment/issues/234)
Tela antes da mudança:
Tela depois da mudança:
Tela de pagamento com descrição:
=> [Payment] Refatorado para usar usuário logado

grails-app/controllers/com/miniasaaslw/controller/BaseController.groovy, grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy, grails-app/controllers/com/miniasaaslw/controller/index/IndexController.groovy, grails-app/controllers/com/miniasaaslw/controller/notification/NotificationController.groovy, grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy, grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy
Agora é usado `getCurrentUser()`, `getCurrentCustomer()` e `getCurrentCustomerId()` quando é preciso utilizar algum deles
Também é adicionado a anotação `GrailsCompileStatic` nos controllers que ainda não tinham
[252](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67357728)
=> [Base Controller] Adicionando métodos para retornar os atributos do usuário logado

grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/views/payment/checkout.gsp, src/main/groovy/com/miniasaaslw/repository/paymentreceipt/PaymentReceiptRepository.groovy
É adicionado um botão para conseguir acessar o comprovante de pagamento quando a cobrança for paga
[256](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67365946)
=> [PaymentReceipt] Adciona botão para acessar o comprovante de pagamento a partir da tela de pagamento

grails-app/i18n/messages_pt_BR.properties
É renomeada algumas mensagens que são enviadas por email
[257](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67366323)
=> [Email] Refatorando mensagens de email

grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy, grails-app/services/com/miniasaaslw/service/user/UserService.groovy, src/main/groovy/com/miniasaaslw/adapters/user/UserAdapter.groovy, src/main/groovy/com/miniasaaslw/utils/EmailUtils.groovy
A partir desse PR, quando um customer alterar seu e-mail, será refletido na tabela de usuário do Spring Boot.
[PR 260](https://github.com/L-W-payments/asaas-payment/pull/260)
[Tarefa 265](https://github.com/L-W-payments/asaas-payment/issues/265)
=> [Customer/User] Alterar e-mail do usuário quando o do customer for alterado

grails-app/conf/application.groovy
Agora sempre que um usuário se loga, é redirecionado para o index
[261](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67374728)
=> [Spring Security] Adicionando configuração pra sempre redirecionar pro index quando logar

grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy, grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy, grails-app/i18n/messages_pt_BR.properties
É adicionado o tratamento de erro aos métodos de listagem
[270](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67492813)
=> Adicionando try catch aos lists

grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy, grails-app/i18n/messages_pt_BR.properties, grails-app/services/com/miniasaaslw/service/user/UserService.groovy, src/main/groovy/com/miniasaaslw/repository/user/UserRepository.groovy
Agora o admin não consegue deletar o proprio usuário, além de remover o usuário logado da listagem de usuários
[260](https://github.com/L-W-payments/asaas-payment/pull/260)
[248](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67220853)
=> [User] Proibir usuário ADMIN de deletar sua conta e ocultar da lista de usuários.

README.md
É adicionado algumas informações ao readme, como rodar o projeto, o que é preciso configurar, além do link para nossos perfis no github
[272](https://github.com/orgs/L-W-payments/projects/1?pane=issue&itemId=67493628)
=> [Readme] Adicionando quickstart do projeto

grails-app/views/error.gsp, grails-app/views/layouts/main.gsp
A página de erros padrão do Grails foi substituída para uma página mais amigável.
[Tarefa 276](https://github.com/L-W-payments/asaas-payment/issues/276)
=> Refatorando página de erro

grails-app/services/com/miniasaaslw/service/emailnotification/EmailNotificationService.groovy
É adicionado o GrailsCompileStatic no service do EmailNotification
[286](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67512430)
=> [EmailNotification] Adiciona GrailsCompileStatic no service

grails-app/init/com/miniasaaslw/BootStrap.groovy
Removendo usuário de testes do Spring Security.
[Tarefa 288](https://github.com/L-W-payments/asaas-payment/issues/288)
=> [Spring Security] Removendo usuário de testes

grails-app/views/index/index.gsp
É removido um "<".
[290](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67513599)
=> [Index] Removendo "<" do card
